blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions / 提问与讨论
    url: https://github.com/auroravoice/user_guide/discussions
    about: Ask questions or discuss usage / 使用问题请先到 Discussion 提问
